export const CLIMATE_PARAMS = {
    precipitation: {
        equatorialWet: { center: 6, sigma: 14, amp: 1500 },
        subtropicalDry: { center: 27, sigma: 9.5, amp: 640 },
        midLatitudeWet: { center: 50, sigma: 13, amp: 520 },
        polarDry: { startLat: 55, span: 30, amp: 480 },
        base: 760,
    },
    prevailingWind: {
        tropicalMaxLat: 30,
        temperateMaxLat: 60,
        tropical: { wx: -1.0, northWy: -0.25, southWy: 0.25 },
        temperate: { wx: 1.0, northWy: 0.2, southWy: -0.2 },
        polar: { wx: -0.85, northWy: -0.15, southWy: 0.15 },
    },
    rainShadow: {
        steps: 6,
        stepLength: 2.4,
        baseScale: 1160,
        monsoonScale: 980,
        desertNormalize: 560,
    },
    coastalExposure: {
        scan: 4,
    },
    coldCoastalDesert: {
        minLat: 15,
        maxLat: 38,
        maxCoastDist: 0.16,
        latCenter: 25,
        latHalfWidth: 13,
        coldSeaBase: 21,
        coldSeaSpan: 9,
    },
    monsoon: {
        minLat: 5,
        maxLat: 35,
        latCenter: 18,
        latSigma: 10,
        warmSeasonBase: 16,
        warmSeasonSpan: 10,
        coastalMaxDist: 0.45,
        directionalBase: 0.45,
        directionalContrastWeight: 0.55,
        inlandFadePow: 1.1,
        rainBoostBase: 260,
        rainBoostInland: 2000,
        minSignalForShadow: 0.04,
        shadowMixBase: 0.55,
        shadowMixWeight: 0.85,
        windMixMax: 0.78,
        windMixWeight: 0.85,
        monsoonWind: { wxOnshore: 1, northWy: -0.22, southWy: 0.22 },
    },
    dryThresholdSeasonAdj: {
        tropicalMaxLat: 23.5,
        temperateMaxLat: 50,
        tropicalAdj: 180,
        temperateAdj: 90,
        polarAdj: 0,
    },
    temperatureZone: {
        ampBase: 2.35,
        ampScale: 13.7,
        ampPow: 1.2,
        polarMinLat: 60,
        forcePolarLat: 76,
        highLatWarmCutoffLat: 68,
        warmPolarThreshold: 9,
        warmPolarThresholdHighLat: 11,
        coldThreshold: -8,
        temperateThresholdLowLat: 15.8,
        temperateThresholdHighLat: 18,
    },
    thermalModel: {
        seaLevelBase: 28.1,
        seaLevelLatGradient: 0.385,
        elevationScaleM: 2200,
        lapseRatePerKm: 4.8,
        islandWarmPow: 1.25,
        islandWarmAmp: 2.5,
    },
    moisture: {
        coastMoisturePow: 1.2,
        coastMoistureAmp: 720,
        islandHumidityPow: 1.8,
        islandHumidityAmp: 260,
        precipMin: 40,
        precipMax: 3500,
    },
    desertPenalty: {
        subtropical: 180,
        interior: 690,
        rainShadow: 2000,
        coldCoastal: 580,
    },
    dryThresholdBonus: {
        subtropical: 45,
        interior: 210,
        rainShadow: 260,
        coldCoastal: 210,
    },
    aridOverride: {
        maxLat: 72,
    },
};
